
- name : this is my 1st playbook
  hosts.ini : servers
  tasks :
    - name : print animal name
      debug :
        msg : "hello i am tiger"
        
    - name : print another animal name
      debug :
        msg : "hello i am lion"
        