- name : loop for automating multiple tasks
  hosts : all
   tasks :
    - name : print numbers
      debug :
        msg : "{{ item }}"
      loop : 
        - 1
        - 2
        - 3
        - 4
        - 5

    - name : print names
      debug :
        msg : "{{item}}"
      loop :
        - tiger
        - lion
        - cat