- name : gather fact from remote system
  hosts : all
  
  tasks :
    - name : collect os name
      debug :
        msg : "{{ansible_distribution}}"
      tags:
        - task2
    - name : collect ip address
      debug :
        msg : "{{ansible_default_ipv4.address}}"
      tags:
        - task3
    - name : print working directory
      debug :
        msg : "{{ansible_env.PWD}}"