- name : this playbook is for apache installation 
  hosts : all
  become : true 

  tasks :
    - name : update
      shell : 
        cmd : apt-get update

    - name : install apache
      apt : 
        name : apache2
        state : latest