- name : this playbook is for apache installation 
  hosts : all
  become : true 

  tasks :
    - name : update
      shell : 
        cmd : apt-get update
    - name : install apache
      shell :
        cmd : apt-get install apache2 -y