- name : this playbook is for apache installation 
  hosts : all
  become : true 

  tasks :
    - name : update
      shell : 
        cmd : apt-get update

    - name : install apache2
      apt :
      - name : apache2
        state : present

    - name : install httpd
      yum :
      - name : httpd
        state : present
