- name : update webserver
  hosts : all
  become : true
  tasks :
    - name : change web page
      copy :
        src : index.html
        dest : /var/www/html/index.html
    
    - name : add oneline
      lineinfile :
        path : /var/www/html/index.html
        regexp : '</h1>'
        line : '<h1> this is 1st line replacement </h1>'

    - name : block of lines files added
      blockinfile :
        path : /var/www/html/index.html
        marker : "<!--- marker for block -->"
        block : |
          - this is promod
          - this is 1st line of block
          - this is 2nd line of block
          
    - name : restart service
      systemd :
        name : apache2
        state : restarted
        enabled : true