- name : this is variable learning
  hosts : all
  #vars : 
   # animal : "tiger"
 #vars_files :
  #  - ./var.txt 
  vars_prompt:
   - name : animal
     prompt : "enter animal name"
    
  tasks :
    - name : print animal 1
      debug :
        msg : "{{animal}}"
    - name : print animal 2
      debug :
        msg : "{{animal}}"
    - name: get hostname
      shell : hostname
        msg : machineName
    - name : print hostname 
      debug :
        msg : "{{machineName.stdout}}"

    - name : print animal 3
      debug :
        msg : "{{animal}}"
      vars:
        animal : "lion"

